---
- name: Deploy Docker Containers
  hosts: webserver
  become: yes
  tasks:
    - name: Update the systemm
      yum:
        update_cache: yes

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start Backend Container
      docker_container:
        name: myBackend
        image: ameni1717/projectbackend
        ports:
          - "3001:3001"
        state: started
        env:
          DB_HOST: "{{ DB_HOST }}"
          DB_USER: "{{ DB_USER }}"
          DB_PASSWORD: "{{ DB_PASSWORD }}"
          DB_NAME: "{{ DB_NAME }}"
          ACCESSKEYID: "{{ AWS_ACCESS_KEY_ID }}"
          SECRETACCESSKEYID: "{{ AWS_SECRET_ACCESS_KEY }}"
          REGION: "{{ REGION }}"
       

    - name: Start Frontend Container
      docker_container:
        name: myFrontend
        image: ameni1717/projectfrontend
        ports:
          - "3000:3000"
        state: started
        env:
          REACT_APP_USER_POOL_ID: "{{ REACT_APP_USER_POOL_ID }}"
          REACT_APP_CLIENT_I: "{{ REACT_APP_CLIENT_ID }}"
          REACT_APP_USER_POOL_ID_FREELANCER : "{{ REACT_APP_USER_POOL_ID_FREELANCER }}"
          REACT_APP_CLIENT_ID_FREELANCER: "{{ REACT_APP_CLIENT_ID_FREELANCER }}"
