---
- name: Deploy Docker Containers
  hosts: webserver
  become: yes
  tasks:
    - name: Update the system
      yum:
        update_cache: yes

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start Backend Container
      docker_container:
        name: myBackend
        image: ameni1717/projectbackend
        ports:
          - "3001:3001"
        state: started
        env:
          host: "{{ DB_HOST }}"
          user: "{{ DB_USER }}"
          password: "{{ DB_PASSWORD }}"
          database: "{{ DB_NAME }}"
          accessKeyId: "{{ AWS_ACCESS_KEY_ID }}"
          secretAccessKey: "{{ AWS_SECRET_ACCESS_KEY }}"
          region: "{{ REGION }}"

    - name: Start Frontend Container
      docker_container:
        name: myFrontend
        image: ameni1717/projectfrontend
        ports:
          - "80:80"
        state: started
        env:
          UserPoolIdcomp: "{{ REACT_APP_USER_POOL_ID }}"
          ClientIdcomp: "{{ REACT_APP_CLIENT_ID }}"
          UserPoolId : "{{ REACT_APP_USER_POOL_ID_FREELANCER }}"
          ClientId: "{{ REACT_APP_CLIENT_ID_FREELANCER }}"
